name: to-pages
on:
  push:
    branches: 
      - main
    # paths-ignore:
    #  - '.github/workflows/**'
permissions:
  contents: write

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v4
    #- name: pause
    #  run : for ((i = 0 ; i < 55 ; i++ )); do echo "$i" && sleep 1; done
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        single-commit: true

# EOF
